// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI (migrate/db push) pakai koneksi langsung — pooler Supabase (pgbouncer)
    // tidak mendukung DDL/prepared statements yang dibutuhkan migrasi.
    url: process.env["DIRECT_URL"] ?? "",
  },
});
